[package]
name = "system-mqtt"
authors = ["James Carl"]
version = "0.3.1"
edition = "2018"
license = "MIT"
readme = "README.md"
description = "Broadcasts system statistics to an mqtt server of your choice. Ideal for home assistant!"
repository = "https://github.com/IamTheCarl/system-mqtt"

[dependencies]
argh = "0.1"
battery = "0.7"
sysinfo = "0.28.1"
keyring = "2.0"
log = "0.4"
systemd-journal-logger = "0.7"
mqtt-async-client = "0.3"
rpassword = "7.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9"
anyhow = "1.0.69"
tokio = { version = "1", features = ["full"] }
url = { version = "2.2", features = ["serde"] }
users = "0.11.0"
simple_logger = "4.0.0"
lm-sensors = "0.3.2"

[package.metadata.deb]
systemd-units = { unit-name = "system-mqtt", unit-scripts = "systemd", enable = true }
depends = ["lm-sensors"]
