services:
  system-mqtt:
#    image: system-mqtt:latest
    image: system-mqtt:gpu-latest
    container_name: system-mqtt
    volumes:
      - ./config/:/app/config/
    environment:
      - RUST_LOG=info
    restart: unless-stopped
    privileged: true
    stop_signal: SIGINT
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
