services:
  system-mqtt:
    image: system-mqtt:latest
    container_name: system-mqtt
    volumes:
      - ./config/:/app/config/
    environment:
      - RUST_LOG=info
    restart: unless-stopped
    privileged: true
    stop_signal: SIGINT
